enhancement

diff --git a/k8s/tasks/kustomize-build.yaml b/k8s/tasks/kustomize-build.yaml
--- a/k8s/tasks/kustomize-build.yaml
+++ b/k8s/tasks/kustomize-build.yaml
@@ -22,6 +22,14 @@ spec:
         echo "image-with-tag: $(params.image-with-tag)"
 
         cd source/k8s
+
+        if [ -f kustomization.yaml ] || [ -f kustomization.yml ] || [ -f Kustomization ]; then
+          echo "Kustomization file found."
+        else
+          echo "Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory:"
+          pwd
+          exit 1
+        fi
         
         kustomize edit set image "*=$(params.image-with-tag)"
         kustomize edit set label "app:$(params.app-namespace)"
